name: GazeKitProject
options:
  bundleIdPrefix: com.omata.gazekit
  deploymentTarget:
    iOS: "16.1"
  defaultConfig: Debug
  groupSortPosition: top
  generateEmptyDirectories: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.1
    TARGETED_DEVICE_FAMILY: "2"  # iPad only
    MARKETING_VERSION: 1.0.1
    CURRENT_PROJECT_VERSION: 2

# No external packages for now - keeping dependencies minimal

targets:
  GazeKit:
    type: framework
    platform: iOS
    sources:
      - Sources/GazeKit
    settings:
      PRODUCT_NAME: GazeKit
      PRODUCT_BUNDLE_IDENTIFIER: com.omata.gazekit.framework
      SKIP_INSTALL: false
      DEFINES_MODULE: true
      DYLIB_INSTALL_NAME_BASE: "@rpath"
      INFOPLIST_FILE: Sources/GazeKit/Info.plist
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: false
    dependencies:
      - sdk: ARKit.framework
      - sdk: SceneKit.framework
      - sdk: UIKit.framework
      - sdk: Foundation.framework
    
  GazeKitDemo:
    type: application
    platform: iOS
    sources:
      - Sources/GazeKitDemo
    resources:
      - Sources/GazeKitDemo/Assets.xcassets
    settings:
      PRODUCT_NAME: GazeKitDemo
      PRODUCT_BUNDLE_IDENTIFIER: com.omata.gazekit.demo.2024
      INFOPLIST_FILE: Sources/GazeKitDemo/Info.plist
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "iPhone Developer"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE_SPECIFIER: ""
      ONLY_ACTIVE_ARCH: true
      ENABLE_BITCODE: false
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
      SKIP_INSTALL: false
    dependencies:
      - target: GazeKit
      - sdk: ARKit.framework
      - sdk: SceneKit.framework
      - sdk: UIKit.framework
      - sdk: Foundation.framework
  
  GazeKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/GazeKitTests
    settings:
      PRODUCT_NAME: GazeKitTests
      PRODUCT_BUNDLE_IDENTIFIER: com.omata.gazekit.tests
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/GazeKitDemo.app/GazeKitDemo
    dependencies:
      - target: GazeKit
      - target: GazeKitDemo
      - sdk: XCTest.framework

schemes:
  GazeKit:
    build:
      targets:
        GazeKit: all
    test:
      targets:
        - GazeKitTests
      
  GazeKitDemo:
    build:
      targets:
        GazeKitDemo: all
        GazeKit: all
    run:
      config: Debug
      executable: GazeKitDemo
      environmentVariables:
        - variable: IDEPreferLogStreaming
          value: "YES"
        - variable: OS_ACTIVITY_MODE
          value: "disable"
    test:
      targets:
        - GazeKitTests
      config: Debug
    profile:
      config: Release
      executable: GazeKitDemo
    analyze:
      config: Debug